// parent-child/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'parent-child';
  data = "x";
  updateData(item : string)
  {
      console.warn(item);
      this.data=item;
  }
}

// React/state11/src/App.js
import {useState} from 'react';
import './App.css';

function App() {
  
  const [data,setData] = useState(0);
  function updateData()
  {
    setData(data+1);
  }
  console.warn("_____________");
  return (
    <div className="App">
     <h1>{data}</h1>
     <button onClick={updateData}>Update Data</button>
    </div>
  );
}

export default App;
